apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: myweb
    name: ubi
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: registry.access.redhat.com/ubi8/ubi:latest
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8/ubi:latest
      name: latest
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: myweb
    name: myweb
